export const shirt1 = require('../../Assets/shirts/shirt1.jpg')
export const shirt2 = require('../../Assets/shirts/shirt2.jpg')
export const shirt3 = require('../../Assets/shirts/shirt3.jpg')
export const shirt4 = require('../../Assets/shirts/shirt4.png')
export const shirt5 = require('../../Assets/shirts/shirt5.jpg')
export const shirt6 = require('../../Assets/shirts/shirt6.jpg')